# Generated by Django 5.0.3 on 2024-03-31 05:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promecapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('idestado', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre_estado', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'db_table': 'estado',
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('IDRol', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre_Rol', models.CharField(max_length=50, unique=True)),
                ('Descripcion', models.TextField()),
            ],
            options={
                'db_table': 'roles',
            },
        ),
        migrations.CreateModel(
            name='TipoPago',
            fields=[
                ('idTipo_pago', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_pago', models.CharField(max_length=45, unique=True)),
            ],
            options={
                'db_table': 'Tipo_pago',
            },
        ),
        migrations.CreateModel(
            name='TipoServicio',
            fields=[
                ('IDTipo_servicios', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre_Servicio', models.CharField(max_length=30, unique=True)),
                ('Descripcion', models.TextField()),
            ],
            options={
                'db_table': 'tipo_servicios',
            },
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='contraseña',
            new_name='Contraseña',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='apellidos',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='cedula',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='correo',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='id',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='nombres',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='numero',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='usuario',
        ),
        migrations.AddField(
            model_name='usuario',
            name='IDUsuario',
            field=models.AutoField(default=11, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='Nombre_Usuario',
            field=models.CharField(default=1, max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='usuario',
            table='usuarios',
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('IDCliente', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=45)),
                ('Apellidos', models.CharField(max_length=45)),
                ('Direccion', models.CharField(max_length=100)),
                ('Telefono', models.CharField(max_length=10, unique=True)),
                ('Correo_Electronico', models.CharField(max_length=50, unique=True)),
                ('IDUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='promecapp.usuario')),
            ],
            options={
                'db_table': 'clientes',
            },
        ),
        migrations.CreateModel(
            name='Citas',
            fields=[
                ('IDCita', models.AutoField(primary_key=True, serialize=False)),
                ('Fecha_Hora', models.DateTimeField()),
                ('Descripcion', models.TextField(null=True)),
                ('IDCliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='promecapp.cliente')),
                ('IDEstado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='promecapp.estado')),
            ],
            options={
                'db_table': 'citas',
            },
        ),
        migrations.CreateModel(
            name='Historial',
            fields=[
                ('IDHistorial', models.AutoField(primary_key=True, serialize=False)),
                ('Descripcion', models.TextField()),
                ('valor', models.IntegerField()),
                ('Fecha', models.DateField()),
                ('IDCliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='promecapp.cliente')),
            ],
            options={
                'db_table': 'historial',
            },
        ),
        migrations.AddField(
            model_name='usuario',
            name='IDRol',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='promecapp.rol'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('IDServicio', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre_Servicio', models.CharField(max_length=30, unique=True)),
                ('Descripcion', models.TextField()),
                ('IDTipo_servicios', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='promecapp.tiposervicio')),
            ],
            options={
                'db_table': 'servicios',
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('IDVenta', models.AutoField(primary_key=True, serialize=False)),
                ('Fecha_Venta', models.DateField()),
                ('Monto_Total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descripcion', models.TextField()),
                ('IDCita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='promecapp.citas')),
                ('IDServicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='promecapp.servicio')),
                ('IDTipo_pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='promecapp.tipopago')),
            ],
            options={
                'db_table': 'venta',
            },
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('idFactura', models.AutoField(primary_key=True, serialize=False)),
                ('Fecha', models.DateField()),
                ('Total', models.DecimalField(decimal_places=2, max_digits=15)),
                ('Descripcion', models.CharField(max_length=100, null=True)),
                ('IDVenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='promecapp.venta')),
            ],
            options={
                'db_table': 'Factura',
            },
        ),
    ]
